# Generated by Django 3.1.1 on 2020-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story5', '0002_auto_20201012_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='sks',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
