# Generated by Django 3.1.1 on 2020-10-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story5', '0003_matakuliah_sks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='sks',
            field=models.CharField(max_length=50),
        ),
    ]
