# Generated by Django 3.1.1 on 2020-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story6', '0002_kegiatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='peserta',
            field=models.ManyToManyField(blank=True, null=True, to='story6.Person'),
        ),
    ]
